`timescale 1ns/1ps

module tb_systolic_top;


    parameter ROWS = 4;
    parameter COLS = 4;
    parameter DATA_WIDTH = 8;
    parameter ACC_WIDTH = 32;
    parameter ADDR_WIDTH = 8;
    parameter K_DIM = 4;
    

    reg clk;
    reg rst_n;
    reg start;
    wire done;
    
    reg host_we_a;
    reg [ADDR_WIDTH-1:0] host_addr_a;
    reg [(ROWS*DATA_WIDTH)-1:0] host_wdata_a;
    
    reg host_we_b;
    reg [ADDR_WIDTH-1:0] host_addr_b;
    reg [(COLS*DATA_WIDTH)-1:0] host_wdata_b;
    
    reg host_re_c;
    reg [ADDR_WIDTH-1:0] host_addr_c;
    wire [(ROWS*COLS*ACC_WIDTH)-1:0] host_rdata_c;


    reg [DATA_WIDTH-1:0] mem_a [0:(ROWS*K_DIM)-1];
    reg [DATA_WIDTH-1:0] mem_b [0:(K_DIM*COLS)-1];
    reg [ACC_WIDTH-1:0]  mem_c_exp [0:(ROWS*COLS)-1];
    
    // Working variables (declared at module level for Verilog-2001)
    integer i, j;
    integer err_cnt;
    integer timeout;
    reg [(ROWS*DATA_WIDTH)-1:0] a_row;
    reg [(COLS*DATA_WIDTH)-1:0] b_row;
    reg [ACC_WIDTH-1:0] act_val;
    reg [ACC_WIDTH-1:0] exp_val;


    systolic_top #(
        .ROWS(ROWS),
        .COLS(COLS),
        .DATA_WIDTH(DATA_WIDTH),
        .ACC_WIDTH(ACC_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) u_top (
        .clk            (clk),
        .rst_n          (rst_n),
        .start          (start),
        .k_dim          (K_DIM[ADDR_WIDTH-1:0]),
        .done           (done),
        .busy           (),
        .fsm_state      (),
        .accumulate     (1'b0),
        .precision_mode (1'b0),
        .clk_gate_en    (1'b0),
        .host_we_a      (host_we_a),
        .host_addr_a    (host_addr_a),
        .host_wdata_a   (host_wdata_a),
        .host_we_b      (host_we_b),
        .host_addr_b    (host_addr_b),
        .host_wdata_b   (host_wdata_b),
        .host_re_c      (host_re_c),
        .host_addr_c    (host_addr_c),
        .host_rdata_c   (host_rdata_c)
    );

    always #5 clk = ~clk;


    initial begin
        // Initialize all signals
        clk = 0;
        rst_n = 0;
        start = 0;
        host_we_a = 0;
        host_addr_a = 0;
        host_wdata_a = 0;
        host_we_b = 0;
        host_addr_b = 0;
        host_wdata_b = 0;
        host_re_c = 0;
        host_addr_c = 0;
        err_cnt = 0;
        timeout = 0;
        
        // Load hex test vectors generated by golden_model.py
        // Vivado XSim looks for these files relative to the simulation
        // run directory. When added as "Data Files" in the Vivado project,
        // they are automatically copied to the correct location.
        // For command-line xsim, copy hex files to the xsim working dir.
        $readmemh("matrix_a.hex", mem_a);
        $readmemh("matrix_b.hex", mem_b);
        $readmemh("matrix_c_expected.hex", mem_c_exp);
        
        // Release reset
        #25;
        @(posedge clk);
        rst_n = 1;
        @(posedge clk);
        

        // At each K-step 'k', the array needs all ROWS activations
        // for column k: A[0][k], A[1][k], ..., A[ROWS-1][k].
        // mem_a layout: row-major, i.e. mem_a[row*K_DIM + col].
        $display("[TB] Loading Input Buffer A...");
        for (i = 0; i < K_DIM; i = i + 1) begin
            a_row = {(ROWS*DATA_WIDTH){1'b0}};
            for (j = 0; j < ROWS; j = j + 1) begin
                a_row[(j*DATA_WIDTH) +: DATA_WIDTH] = mem_a[j*K_DIM + i];
            end
            @(posedge clk);
            host_we_a = 1;
            host_addr_a = i[ADDR_WIDTH-1:0];
            host_wdata_a = a_row;
        end
        @(posedge clk);
        host_we_a = 0;
        

        // At each K-step 'k', the array needs all COLS weights
        // for row k: B[k][0], B[k][1], ..., B[k][COLS-1].
        // mem_b layout: row-major, i.e. mem_b[row*COLS + col].
        $display("[TB] Loading Weight Buffer B...");
        for (i = 0; i < K_DIM; i = i + 1) begin
            b_row = {(COLS*DATA_WIDTH){1'b0}};
            for (j = 0; j < COLS; j = j + 1) begin
                b_row[(j*DATA_WIDTH) +: DATA_WIDTH] = mem_b[i*COLS + j];
            end
            @(posedge clk);
            host_we_b = 1;
            host_addr_b = i[ADDR_WIDTH-1:0];
            host_wdata_b = b_row;
        end
        @(posedge clk);
        host_we_b = 0;
        

        $display("[TB] Starting computation...");
        @(posedge clk);
        start = 1;
        @(posedge clk);
        
        // Wait for done with timeout protection
        timeout = 0;
        while (done !== 1'b1 && timeout < 2000) begin
            @(posedge clk);
            timeout = timeout + 1;
        end
        
        if (timeout >= 2000) begin
            $display("[TB] ERROR: Timeout after %0d cycles waiting for done!", timeout);
            $finish;
        end
        
        $display("[TB] Computation done after %0d cycles.", timeout);
        @(posedge clk);
        start = 0;
        

        @(posedge clk);
        host_re_c = 1;
        host_addr_c = 0;
        @(posedge clk);  // buffer read latency: 1 cycle
        @(posedge clk);  // data valid here
        host_re_c = 0;
        

        
        for (i = 0; i < ROWS; i = i + 1) begin
            for (j = 0; j < COLS; j = j + 1) begin
                act_val = host_rdata_c[((i*COLS + j)*ACC_WIDTH) +: ACC_WIDTH];
                exp_val = mem_c_exp[i*COLS + j];
                
                if (act_val !== exp_val) begin
                    $display("  MISMATCH C[%0d][%0d]: Expected=%0d  Actual=%0d",
                             i, j, $signed(exp_val), $signed(act_val));
                    err_cnt = err_cnt + 1;
                end
            end
        end
        
        if (err_cnt == 0) begin
            $display("\n[ PASS ] SIMULATION PASSED: All %0d results correct.", ROWS*COLS);
        end else begin
            $display("\n[ FAIL ] SIMULATION FAILED: %0d mismatches out of %0d.", err_cnt, ROWS*COLS);
        end
        
        #20;
        $finish;
    end

endmodule
